### ISSUE TITLE
[HANOI] Full-time Golang Developer at RAKUNA

### ISSUE THREAD

**Issue by minhtldm** [golang-vietnam/jobs#10]
## Location
* Hoan Kiem district, Hanoi, Vietnam

## Requirements
* Want to use Golang to resolve real-world problems
* Experienced in software development
* Love startup environment

### Must Have
* 1+ years working with Golang
* Databases: MySQL/PostgreSQL
* Operating System: Linux/Unix, MacOS
### Ideally
* Master at least one modern programming languages
* Experience in web development
* Used to work with Golang Framework (Revel, Beego, Iris ...)
* Have knowledge and skills about microservices
* Good background about process, thread & concurency
* Experiences in cloud services: Amazon Web Service, Google Cloud Service
### Responsibilities
* Create new services support event recruiting process
* Provide and implement solutions to improve system performance

## Benefits
* Performance-based and negotiable salary (heavily depends on your skills.
* You will have endless opportunities to challenge yourself through various projects and training
* Free lunches!
    
## Contact
* Please send your resumés/CVs to minh@rakuna.co (only qualified candidates will be contacted).
* More info: Rakuna (www.rakuna.co) is a Silicon Valley tech company that specializes in Campus Recruiting Software. We are looking to expand our team and is open to any opportunity conversations with all developers in Vietnam.

**Comment by fuatto** [comment]
Lapsed!
